src/NodeCubeChat/Controllers/SurveyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using NodeCubeChat.Models;
using NodeCubeChat.Models.AdminViewModels;
using NodeCubeChat.Models.SurveyViewModels;

namespace NodeCubeChat.Controllers
{
    public class SurveyController : Controller
    {
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly UserManager<ApplicationUser> _UserManager;
        private ChatContext _context;

        public SurveyController(
        SignInManager<ApplicationUser> signInManager, UserManager<ApplicationUser> userManager, ChatContext context)
        {
            _signInManager = signInManager;
            _UserManager = userManager;
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            List<Survey> EligableSurvey = new List<Survey>();

            var currentUser = await _UserManager.GetUserAsync(User);
            int UserAge = DateTime.Now.Year - currentUser.DateOfBirth.Year;

            int rating = 0;

            rating += _context.UserRatings.Where(item => item.RatedUser == currentUser.UserName && item.Score == true).Count();
            rating -= _context.UserRatings.Where(item => item.RatedUser == currentUser.UserName && item.Score == false).Count();

            bool UserPositiveProfile = (rating >= 0) ? true : false;

            var FilteredSurvey = (from item in _context.Surveys where (item.RequiredMinAge <= UserAge) && (item.RequiredMaxAge >= UserAge) && (!item.RequiredPositiveUserRating || UserPositiveProfile) select item).ToList();
            
            foreach(Survey survey in FilteredSurvey)
            {
                switch(survey.RequiredGender)
                {
                    case 0:
                        EligableSurvey.Add(survey);
                        break;
                    case 1:
                        if(currentUser.Gender == 1)
                            EligableSurvey.Add(survey);
                        break;
                    case 2:
                        if (currentUser.Gender == 2)
                            EligableSurvey.Add(survey);
                        break;

                        
                }
            }

            //Filter out completed and on-cooldown surveys
            var InvalidSurveys = (from item in _context.SurveyStatistics
                                      where (item.ParticipantUserName == User.Identity.Name && item.FinishedSurvey == true) || (item.ParticipantUserName == User.Identity.Name && DateTime.Now < item.CoolDownPeriod)
                                      select item.SurveyId).ToList<int>();

            int surveysfiltered = 0;

            for(int i=0; i<EligableSurvey.Count;i++)
            {
                if(InvalidSurveys.Any(x => x == EligableSurvey[i-surveysfiltered].SurveyId))
                {
                    EligableSurvey.Remove(EligableSurvey[i-surveysfiltered]);
                    surveysfiltered++;
                }
            }
            

            return View(EligableSurvey);
        }

        [HttpGet]
        public IActionResult Execute(int Id=0)
        {
            Survey SelectedSurvey = (from item in _context.Surveys where item.SurveyId == Id select item).SingleOrDefault();

            if (SelectedSurvey == null)
                return RedirectToAction("Home", "Index");

            var stat = new SurveyStatistic
            {
                SurveyId = Id,
                TimeStamp = DateTime.Now,
                CoolDownPeriod = DateTime.Now.AddDays(7),
                FinishedSurvey = false,
                ParticipantUserName = User.Identity.Name,
            };

            _context.SurveyStatistics.Add(stat);

            _context.SaveChanges();

            List<SurveyQuestionModel> surveyquestions = new List<SurveyQuestionModel>();
            List<SurveyOptionModel> questionoptions = new List<SurveyOptionModel>();


            List<SurveyQuestion> SelectedSurveyQuestions = (from item in _context.SurveyQuestions where item.SurveyId == SelectedSurvey.SurveyId select item).ToList();

            foreach(SurveyQuestion question in SelectedSurveyQuestions)
            {
                questionoptions = new List<SurveyOptionModel>();

                if (question.Type=="Text")
                {
                    var text = new SurveyOptionModel
                    {
                        OptionId = null,
                        Text = "",
                        Title = "",
                        Checked = false
                    };

                    questionoptions.Add(text);

                    var textqmodel = new SurveyQuestionModel
                    {
                        Title = question.Title,
                        Description = question.Description,
                        QuestionId = question.SurveyQuestionId,
                        Options = questionoptions,
                        Type = question.Type
                    };

                    surveyquestions.Add(textqmodel);
                    continue;
                }

                List<SurveyOption> QuestionOptions = (from item in _context.SurveyOptions where item.SurveyQuestionId == question.SurveyQuestionId select item).ToList();

                foreach(SurveyOption option in QuestionOptions)
                {

                    var multipleoption = new SurveyOptionModel
                    {
                        OptionId = option.SurveyOptionId,
                        Text = null,
                        Title = option.Title,
                        Checked = false
                    };
                    questionoptions.Add(multipleoption);
                }

                var multipleqmodel = new SurveyQuestionModel
                {
                    Title = question.Title,
                    Description = question.Description,
                    QuestionId = question.SurveyQuestionId,
                    Options = questionoptions,
                    Type = question.Type
                };

                surveyquestions.Add(multipleqmodel);
            }

            var model = new SurveyModel
            {
                Title = SelectedSurvey.Title,
                Description = SelectedSurvey.Description,
                SurveyId = SelectedSurvey.SurveyId,
                Questions = surveyquestions
            };

            return View(model);
        }
        

        [HttpPost]
        public async Task<IActionResult> Execute(SurveyModel model)
        {
            var user = await _UserManager.GetUserAsync(User);

            var stat = (from item in _context.SurveyStatistics
                        where item.SurveyId == model.SurveyId && item.ParticipantUserName == User.Identity.Name
                        select item).SingleOrDefault();



            return View("ThankYou");
        }
        public async Task<ActionResult> GetUserInfo()
        {
            var user = await _UserManager.GetUserAsync(User);
            return Json(user);
        }

        public async Task<Survey> GetAnEligableSurvey()
        {
            List<Survey> EligableSurveys = new List<Survey>();

            var currentUser = await _UserManager.GetUserAsync(User);
            int UserAge = DateTime.Now.Year - currentUser.DateOfBirth.Year;

            int rating = 0;

            rating += _context.UserRatings.Where(item => item.RatedUser == currentUser.UserName && item.Score == true).Count();
            rating -= _context.UserRatings.Where(item => item.RatedUser == currentUser.UserName && item.Score == false).Count();

            bool UserPositiveProfile = (rating >= 0) ? true : false;

            var FilteredSurvey = (from item in _context.Surveys where (item.RequiredMinAge <= UserAge) && (item.RequiredMaxAge >= UserAge) && (!item.RequiredPositiveUserRating || UserPositiveProfile) select item).ToList();

            foreach (Survey survey in FilteredSurvey)
            {
                switch (survey.RequiredGender)
                {
                    case 0:
                        EligableSurveys.Add(survey);
                        break;
                    case 1:
                        if (currentUser.Gender == 1)
                        EligableSurveys.Add(survey);
                        break;
                    case 2:
                        if (currentUser.Gender == 2)
                        EligableSurveys.Add(survey);
                        break;


                }
            }

            if(EligableSurveys.Count == 0)
            {
                return null;
            }

            return EligableSurveys[new Random().Next(0, EligableSurveys.Count - 1)];
        }

    }
}

src/NodeCubeChat/Views/Survey/Execute.cshtml
@using NodeCubeChat.Models.SurveyViewModels;

@model SurveyModel
@{
    ViewData["Title"] = "Surveys";

}

<div class="Manage-Container">
    <form asp-controller="Survey" asp-action="Execute" method="post">
        <input type="hidden" asp-for="SurveyId" value="@Model.SurveyId" />
        <input type="hidden" asp-for="Title" value="@Model.Title" />
        <h2>@Model.Title</h2>
        <hr />
        <input type="hidden" asp-for="Description" value="@Model.Description" />
        <h3>@Model.Description</h3>
            <div class="row">

            @for (int i = 0; i < Model.Questions.Count; i++)
            {
                <input type="hidden" asp-for="Questions[i].Title" value="@Model.Questions[i].Title" />
                <input type="hidden" asp-for="Questions[i].Description" value="@Model.Questions[i].Description" />
                <input type="hidden" asp-for="Questions[i].QuestionId" value="@Model.Questions[i].QuestionId" />

                <label class="col-md-12 control-label">@Model.Questions[i].Title</label>
                <p class="col-md-12 control-label">@Model.Questions[i].Description</p>
                <div class="col-xs-12">
                    @for (int j = 0; j < Model.Questions[i].Options.Count; j++)
                    {
                        <input type="hidden" asp-for="Questions[i].Options[j].OptionId" value="@Model.Questions[i].Options[j].OptionId" />
                        <input type="hidden" asp-for="Questions[i].Options[j].Title" value="@Model.Questions[i].Options[j].Title" />
                    }
                    @switch (Model.Questions[i].Type)
                    {
                        case "Text":
                            <div class="form-group">
                                <div class="col-md-12">
                                    <div class="input-group">
                                        <span class="input-group-addon"><span class="glyphicon glyphicon-user"></span></span>
                                        @for (int j = 0; j < Model.Questions[i].Options.Count; j++)
                                        {
                                            @Html.TextAreaFor(m => m.Questions[i].Options[j].Text, new { @required = "required" });
                                        }
                                    </div>
                                </div>
                            </div>
                            break;
                        case "Select":

                            <div class="form-group">
                                <div class="col-md-12">
                                    <div class="input-group">
                                        <select asp-for="Questions[i].SelectAnswer" class="form-control" required>
                                            @for(int j=0; j < Model.Questions[i].Options.Count;j++)
                                            {
                                                <option value="@Model.Questions[i].Options[j].OptionId">@Model.Questions[i].Options[j].Title</option>
                                            }
                                        </select>
                                    </div>
                                </div>
                            </div>
                            break;
                        case "Checkbox":

                            @for (var j = 0; j < Model.Questions[i].Options.Count(); j++)
                            {
                                <div class="form-group">
                                    <div class="form-control">
                                        @Html.HiddenFor(chk => chk.Questions[i].Options[j].OptionId)
                                        @Html.CheckBoxFor(chk => chk.Questions[i].Options[j].Checked)
                                        @Html.DisplayFor(chk => chk.Questions[i].Options[j].Title)
                                    </div>
                                </div>
                            }

                            break;
                        case "Radio":

                            @for (var j = 0; j < Model.Questions[i].Options.Count(); j++)
                            {
                                <div class="form-group">
                                    <div class="checkbox form-control">
                                        @Html.HiddenFor(chk => chk.Questions[i].Options[j].OptionId)
                                        @Html.RadioButtonFor(chk => chk.Questions[i].SelectAnswer, Model.Questions[i].Options[j].OptionId)
                                        @Html.DisplayFor(chk => chk.Questions[i].Options[j].Title)
                                    </div>
                                </div>
                            }

                            break;
                    }
                </div>
            }
        </div>
        <div class="col-xs-12">

            <div class="form-group">
                <div class="">
                    <input type="submit" name="Submit" value="Submit Survey" class="form-control btn btn-block btn-success" />
                </div>
            </div>
        </div>
    </form>
</div>

src/NodeCubeChat/Views/Survey/Index.cshtml
@model List<Survey>
@{
    ViewData["Title"] = "Surveys";

}

<div class="Manage-Container">
    <h2>@ViewData["Title"]</h2>
    <hr />
    <h3>Eligable surveys</h3>
    <div class="row">
        <div>
            <a asp-action="AddCompany" asp-controller="Admin" class="btn btn-default">Add new company</a>
        </div>
        @for (int i = 0; i < Model.Count; i++)
        {
            <div class="col-xs-12">
                    <div id="formGroupusername" class="form-group">
                        <label for="username" class="col-md-2 control-label">@Model[i].Title</label>
                        <div class="col-md-9">
                            <div class="input-group">
                                <span class="input-group-addon"><span class="glyphicon glyphicon-user"></span></span>
                                <input id="username" name="username" type="text" class="form-control" value="@Model[i].Description" />
                            </div>
                            <span id="msgusername" class="help-block"></span>
                        </div>
                        <div class="col-md-1">
                            <a href="/Survey/Execute/@Model[i].SurveyId" class="btn btn-link">Start survey</a>
                        </div>
                    </div>
            </div>
        }
    </div>
</div>